config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'
  			 				 }

  resources :users, only: [:show, :destroy, :edit, :create]	
  resources :rooms
  resources :photos

  resources :room do
    resources :reservations, only: [:create, :destroy]
  end		

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  patch 'users/:id', controller: 'users', action: :update
  put 'users/:id', controller: 'users', action: :update

  get '/problem_tickets' => 'admin#problem_tickets'

  get '/create_user' => 'admin#create'

  get '/admin_panel' => 'admin#admin_panel'

  get '/admin_panel_users' => 'admin#admin_panel_users'

  get '/admin_panel_bookings' => 'admin#admin_panel_bookings'

  get '/search_for_bookings' => 'admin#bookings_search'

  get '/search_for_users' => 'admin#users_search'

  put '/edit_user' => 'user#update'

  get '/admin_user_edit' => 'users#admin_user_edit'

end

app/views/admin/admin_panel.html.erb
<!-- Displays the layout for admin_panel -->
<div class="row">
  <div class="col-md-3">
	<ul class="sidebar-list">
	  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link active" %></li>
	  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link" %></li>
	</ul>
  </div>
  <div class="col-md-9">
		<div class="panel panel-default">
		  <div class="panel-heading">
			General Information
		  </div>
		  <div class="panel-body">
			
			<div class="row">
			  <div class="col-md-2">
				<h4><i class="fa fa-user"></i> User Information</h4>
			  </div>
			  <!-- Display User count -->
			  <div class="col-md-7">
				<h4>Total Users: <%= @users.count %></h4>
				<h4></h4>
			  </div>
			</div>

			<hr>

			<div class="row">
			  <div class="col-md-2">
				<h4><i class="fa fa-book"></i> Reservation Information</h4>
			  </div>
			  <!-- Display Reservation count -->
			  <div class="col-md-7">
				<h4>Total Reservations: <%= @reservations.count %></h4>
			  </div>
			</div>



		  </div>
		</div>
	  </div>
  </div>

app/views/admin/admin_panel_bookings.html.erb
<!-- Displays the layout for admin_panel_bookings -->
<div class="row">
  <div class="col-md-3">
	<ul class="sidebar-list">
	  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link active" %></li>
	  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link" %></li>
	</ul>
  </div>
  <div class="col-md-9">
	<div class="panel panel-default">
	  <div class="panel-heading">
		All Reservations
	  </div>
	  <div class="panel-body">
		<!-- Create a form For each reservation   -->
		<% @reservations.each do |reservation| %>
		  <div class="row">
			<div class="col-md-2">
			  <!-- Display Reservation total -->
			  <h4>Total: $<%= reservation.total %></h4>
			</div>
			<div class="col-md-7">
			  <!-- Display reservation start date -->
			  <h4>Start Date: <%= reservation.start_date %></h4>
			  <!-- Display reservation end date -->
			  <h4>End Date: <%= reservation.end_date %></h4>
			  <!-- Display reservation user id -->
			  <h4>Reserver ID: <%= reservation.user_id %> </h4>
			  <!-- Display reservation id -->
			  <h4>Reservation ID: <%= reservation.id %></h4>
			</div>
			<div class="row-space-2"> 
			  <h4>Created: <%= reservation.created_at %></h4>  
			  <h4>Updated: <%= reservation.updated_at %></h4>
			</div>
			<div class="row-space-2">
				  <%= button_to "Delete", room_path(reservation), method: :delete, data: { confirm: "Are you Sure?"}, class: 'btn btn-primary' %>					
			</div>
		  </div>
		  <hr>
		<% end %>

	  </div>
	</div>
  </div>
</div>

app/views/admin/admin_panel_users.html.erb
<!-- Displays the layout for admin_panel_users -->
	<div class="row">
	  <div class="col-md-3">
		<ul class="sidebar-list">
		  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link active" %></li>
		  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link" %></li>
		</ul>
	  </div>
	  <div class="col-md-9">
		<div class="panel panel-default">
		  <div class="panel-heading">
			All Users
			<div class="pull-right">
			  <%= link_to "Create New User", create_user_path, class: 'btn btn-primary' %>
		    </div>
		  </div>
		  
		  <div class="panel-body">
		  	<div class="col-md-12">

			<% @users.each do |user| %>

			  <div class="row">
					<div class="col-md-2">
					<!-- Display user image -->
					  <%= image_tag avatar_url(user), class: "img-circle avatar-medium" %>
					</div>
					<br>
					<div class="col-md-5">
					<!-- Display user full name -->
					  <h4>Name: <%= user.fullname %></h4>
					  <!-- Display user email -->
					  <h4>Email: <%= user.email %></h4>
					  <!-- Display user id -->
					  <h4>Id Number: <%= user.id %></h4>
					  <% if(user.is_admin? == true) %>
						<h4>Admin</h4>
					  <% else %>
						<h4>Normal User</h4>
					  <% end %>
					</div>
					<br>
					<div class="col-md-4">
					<!-- Display a button to user profile -->
					 <div class="row-space-2">
					  <%= link_to "View Profile", user_path(user), class: 'btn btn-primary wide' %>
					 </div>
					
					<!-- Display button to delete user -->
					 <div class="row-space-2">
					  <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you Sure?"}, class: 'btn btn-primary wide' %>
					 </div>

					<!-- Display button for updating user info -->
					 <div class="row-space-2">
					  <%= link_to "Update User Information", edit_user_path(user), class: 'btn btn-primary wide' %>
					 </div>
				    </div>
			  </div>

			  <hr>
			<% end %>

		  </div>
		</div>
	  </div>
	</div>

app/views/admin/bookings_search.html.erb
<!-- Displays the layout for bookings_search -->
<div class="row">
	  <div class="col-md-3">
		<ul class="sidebar-list">
		  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link active" %></li>
		  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link" %></li>
		</ul>
	  </div>
	  <div class="col-md-9">
		<div class="panel panel-default">
		  <div class="panel-heading">

		  </div>
		  <div class="panel-body">
			
			<div class="col-md-12">

		      <%= search_form_for @search, url: search_for_bookings_path do |f| %>
	    
		        <div class="row">
		          <div class="col-md-6">
		          <!-- Display a label -->
					<%= f.label "Reservation ID, Reserver's ID, or Room ID contains" %>:
		          </div>
			      <div class="col-md-3">
			      <!-- Display a search field for id, room id, or user id  -->	        
					<%= f.search_field :id_or_room_id_or_user_id_cont %> 					
				  </div>
				  <div class="col-md-3">
					<%= f.submit "Search", class: "btn btn-primary" %>
				  </div>
				</div>

	          <% end %>

	          <hr>
	        </div>

		 
		    <% @arrResult.each do |reservation| %>

			  <div class="row">
			    <div class="col-md-12">
			    <!-- Display reservation start date -->
				  <h4>Start Date: <%= reservation.start_date %></h4>
				  <!-- Display reservation end date -->
				  <h4>End Date: <%= reservation.end_date %></h4>
				  <!-- Display reservation total -->
				  <h4>Total: $<%= reservation.total  %></h4>
			    </div>
			  </div>

		    <% end %> 

		  </div>
		</div>
	  </div>

</div>



<script>
  $(function() {
  	$("#start_date").datepicker({
  		dateFormat: 'dd-mm-yy',
  		minDate: null,
  		maxDate: '3m',
  		onSelect: function(selected) {
  			$('#end_date').datepicker("option", "minDate", selected);
  			$('#end_date').attr('disabled', false);
  		}
  	});

  	$("#end_date").datepicker({
  		dateFormat: 'dd-mm-yy',
  		minDate: null,
  		maxDate: '3m',
  		onSelect: function(selected) {
  			$('#start_date').datepicker("option", "maxDate", selected);
  		}
  	});
  })
</script>

app/views/admin/create_user.html.erb
<!-- Displays the layout for create_user -->
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">

    <h2>Sign up</h2>

    <%= form_for User.new, url: create_user_path do |f| %>
      <%= render 'shared/devisemes' %>

      <div class="form-group">
      <!-- Display a text field for fullname -->
        <%= f.text_field :fullname, :class => 'form-control', :placeholder => 'Full Name', autofocus: true %>
      </div>

      <div class="form-group">
      <!-- Display display a text field for email -->
        <%= f.email_field :email, :class => 'form-control', :placeholder => 'Email' %>
      </div>

      <div class="form-group">
        <% if @validatable %>
        <!-- Determine is password is valid  -->
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <!-- Display a field for password -->
        <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password', autocomplete: "off" %>
      </div>

      <div class="actions">
      <!-- Display a button for save -->
        <%= f.submit "Sign up", :class => "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/problem_tickets.html.erb
<!-- Displays the layout for problem_tickets -->
<div class="row">
  <div class="col-md-3">
	<ul class="sidebar-list">
	  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link" %></li>
	  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link active" %></li>
	</ul>
  </div>
  <div class="col-md-9">
		<div class="panel panel-default">
		  <div class="panel-heading">
			Problem Tickets
		  </div>
		  <div class="panel-body">

			<% @conversations.each do |conversation| %>
			  <% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>

			  <%= link_to conversation_messages_path(conversation) do %>

				  <div class="row conversation">
					<div class="col-md-2">
					<!-- Display the other users image -->
					  <%= image_tag avatar_url(other), class: "img-circle avatar-medium" %>
					</div>
					<div class="col-md-2">
					<!-- Display other users fullname -->
					  <%= other.fullname %><br>
					  <!-- Display the time of last message -->
					  <%= conversation.messages.last.message_time %>
					</div>
					<div class="col-md-8">
					<!-- Display the content of the last message -->
					  <%= conversation.messages.last.content %>
					</div>
				  </div>

			  <% end %>
		    <% end %>
				
		</div>

			

		  </div>
		</div>
	  </div>
  </div>

app/views/admin/users_search.html.erb
 <!-- Displays the layout for users_search -->
  <div class="row">  
      <div class="col-md-3">
		<ul class="sidebar-list">
		  <li class="sidebar-item"><%= link_to "Admin Panel Overview", admin_panel_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "All Users", admin_panel_users_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "All Reservations", admin_panel_bookings_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Search For Users", search_for_users_path, class: "sidebar-link active" %></li>
		  <li class="sidebar-item"><%= link_to "Search for Reservations", search_for_bookings_path, class: "sidebar-link" %></li>
		  <li class="sidebar-item"><%= link_to "Problem Tickets",  problem_tickets_path, class: "sidebar-link" %></li>
		</ul>
	  </div>
	  <div class="col-md-9">
	    <div class="panel panel-default">
	      <div class="panel-heading">

	      </div>
	      <div class="panel-body">
			
			<div class="col-md-12">

				  <%= search_form_for @search, url: search_for_users_path do |f| %>
			    
				    <div class="row">
					  <div class="col-md-4">
					  <!-- Display a label for fullname and email -->
						<%= f.label :fullname_or_email_cont %>:
					  </div>
					  <div class="col-md-3">
					  <!-- Display a search field for fullname or email -->
						<%= f.search_field :fullname_or_email_cont %>
					  </div>
					  <div class="col-md-3">
					  <!-- Display a save button -->
						<%= f.submit "Search", class: "btn btn-primary" %>
					  </div>
				    </div>

			      <% end %>

			      <hr>
			    </div>

				 
				<% @arrResult.each do |user| %>

					  <div class="row">
						<div class="col-md-2">
						<!-- Display users image -->
						  <%= image_tag avatar_url(user), class: "img-circle avatar-medium" %>
						</div>
						<div class="col-md-7">
						<!-- Display users fullname -->
						  <h4>Name: <%= user.fullname %></h4>
						  <!-- Display  -->
						  <h4>Email: <%= user.email %></h4>
						  <!-- Display user id -->
						  <h4>Id Number: <%= user.id %></h4>
						  <!-- Display if user is an admin -->
						  <% if(user.is_admin? == true) %>
							<h4>Admin</h4>
						  <% else %>
						  	<h4>Normal User</h4>
						  <% end %>
						</div>
						<div class="col-md-3">
						<!-- Display view profile button -->
						 <div class="row-space-2">
						  <%= link_to "View Profile", user_path(user), class: 'btn btn-primary wide' %>	
						 </div>
						  <!-- Display delete user button -->
						 <div class="row-space-2">
						  <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you Sure?"}, class: 'btn btn-primary wide' %>
						 </div>	
						</div>
					  </div>
						
					  <hr>
				<% end %>

	      </div>
	
		</div>
	  </div>	

  </div>