config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, 
  			 :path => '', 
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'
  			 				 }

  resources :users, only: [:show, :destroy, :edit, :create]	
  resources :rooms
  resources :photos

  resources :room do
    resources :reservations, only: [:create, :destroy]
  end		

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  patch 'users/:id', controller: 'users', action: :update
  put 'users/:id', controller: 'users', action: :update

  get '/problem_tickets' => 'admin#problem_tickets'

  get '/create_user' => 'admin#create'

  get '/admin_panel' => 'admin#admin_panel'

  get '/admin_panel_users' => 'admin#admin_panel_users'

  get '/admin_panel_bookings' => 'admin#admin_panel_bookings'

  get '/search_for_bookings' => 'admin#bookings_search'

  get '/search_for_users' => 'admin#users_search'

  put '/edit_user' => 'user#update'

  get '/admin_user_edit' => 'users#admin_user_edit'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </button>
          
            <a class="navbar-brand" href=https://f5afb0ca.ngrok.io>Levart</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
            </div>
          <% end %>
          <ul class="nav navbar-nav navbar-right">

            <% if(!user_signed_in?) %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
                  <%= current_user.fullname %> <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to "Your Listings", rooms_path %></li>
                  <li><%= link_to "Your Reservations", your_reservations_path %></li>
                  <li><%= link_to "Your Trips", your_trips_path %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
            
            <% if user_signed_in? && current_user.is_admin == false %>
              <li>
                <%= link_to conversations_path(sender_id: current_user.id, recipient_id: 11), method: 'post' do %>
                  <i class="fa fa-envelope-o"></i> My Problem Tickets
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home fa-lg"></i> Home
              <% end %>
            </li>
            <li>
              <% if(user_signed_in?) %>
                <% if(current_user.is_admin? == true) %>
                  <%= link_to admin_panel_path do %>
                    <i class="fa fa-address-card"></i> Admin Panel
                  <% end %>
                <% end %>
              <% end %> 
            </li>
             


          </ul>
   
        </div><!--/.nav-collapse -->
      </div>
    </nav>